### ISSUE TITLE
如何在GlViewer中显示文字？

### ISSUE THREAD

**Issue by mjlsuccess** [RobotSDK/SDK#1]
何组长，
 我想在GLViewer中显示文字，现在的代码如下：

```
glPushMatrix();
glTranslatef(100, 100, 0);
glview->renderText(-100,100,0, "wwdsdasdas");
glPopMatrix();
```

显示的效果（在左下角）：
![image](https://cloud.githubusercontent.com/assets/8281407/7744825/58bcfee2-ffe1-11e4-8a15-f8bda8501d51.png)

我想问一下为啥glTranslatef函数没起作用啊？

**Comment by alexanderhmw** [comment]
如何知道glTranslate没有起作用？

**Comment by mjlsuccess** [comment]
把glTranslate去掉，显示的位置还在左下角啊

**Comment by alexanderhmw** [comment]
GLViewer应该带原点坐标轴，把坐标轴显示一下，现在这个图没有参考系，完全不知道画在哪了。

**Comment by alexanderhmw** [comment]
另外，你在操作矩阵的时候，是否设置了当前矩阵为模型视图， glMatrixMode(GL_MODELVIEW)。

**Comment by mjlsuccess** [comment]
我尝试了一下glMatrixMode(GL_MODELVIEW)没效果啊

```
glMatrixMode(GL_MODELVIEW);
glPushMatrix();
//glMatrixMode(GL_MODELVIEW);
glTranslatef(50, 50, 0);
glview->renderText(0,0,0, "wwdsdasdas");
glPopMatrix();
```

结果如下：
![image](https://cloud.githubusercontent.com/assets/8281407/7747610/d00314d4-ffee-11e4-941f-d636b997ef44.png)

**Comment by alexanderhmw** [comment]
首先，你要渲染的文字已经不在<0,0,0>了，说明存在位移。
然后，这个位移的方向都是负的，不是(50.50,0)
那么接下来就要检查mode_view_matrix是不是我们想要的：
glGet with argument GL_MODELVIEW_MATRIX

另外，你这个绘制是在用displaylist吗，那问题就来了，GLViewer对显示列表的矩阵变换应该使用glviewer提供的函数，而不是opengl的函数：

```
void setDisplayListScale(GLuint listid, double sx, double sy, double sz, bool islistid=1);
void setDisplayListRotation(GLuint listid, double rx, double ry, double rz, bool islistid=1);
void setDisplayListTranslation(GLuint listid, double tx, double ty, double tz, bool islistid=1);
void setDisplayListTransform(GLuint listid, Eigen::Matrix4d transform, bool islistid=1);
```

具体的看GLViewer的源代码：
https://github.com/RobotSDK/SDK/blob/master/GLViewer/glviewer.h#L72

**Comment by mjlsuccess** [comment]
glGet with argument GL_MODELVIEW_MATRIX 这句话是什么意思啊，没找到glGet这个函数啊。
另外，我尝试了一下函数setDisplayListTranslation，它只是让我画的其他内容的坐标系产生了变化，但对显示的字体坐标系没有效果啊。下面是完整的代码：

```
glNewList(displaylistbase,GL_COMPILE_AND_EXECUTE);

Point2D startPt;
startPt.x = 60;// cos
startPt.y = 10;//
frenet2Cart_test.generateOfflineTraj();
frenet2Cart_test.generateOnlineTraj(startPt, traj);

glPushMatrix();
glPointSize(10);
glColor3f(1,0,0);
glBegin(GL_POINTS);
glVertex3f(startPt.x, startPt.y, 0);
glEnd();
glPopMatrix();


glPushMatrix();
glview->setDisplayListTranslation(displaylistbase, 30, 30, 0);
glview->renderText(0,0,0, "wwdsdasdas");
glPopMatrix();
glEndList();
```

输出结果：

![image](https://cloud.githubusercontent.com/assets/8281407/7748487/9d96f908-fff7-11e4-96ca-8e8e18637947.png)

**Comment by alexanderhmw** [comment]
麻烦你到网上搜一下glGet，网上讲的很明白，无非是获取数值类型不同，后缀也不同。
另外用了glviewer的变换函数，就不要再用OpenGL 的矩阵操作了。两个都用，肯定出问题。
所以你先用opengl的矩阵变换，用glget检查一下。是不是得到你想要的变换矩阵。
再用glviewer的变换函数。
还有，你使用glviewer的makecurrent函数没有，源代码没见到。

**Comment by alexanderhmw** [comment]
还有，glviewer的变换是对整个显示列表的最终变换，和opengl的矩阵操作不同。所以，会出现对其它东西产生变换。你要单独变换文字，需要让文字在单独的显示列表。glviewer的变换设置可以在任意地方，不需要在glnewlist和glendlist之间，因为他不是过程操作，而是一个最重变换。

**Comment by alexanderhmw** [comment]
@mjlsuccess 问题是否解决？如果解决，请及时关闭问题
